#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# iOS 白牌換裝腳本 — 對 home-assistant/iOS pin tag 的乾淨 checkout 執行一次
#
#   bash Tools/brand/rebrand-ios.sh Tools/brand/simon-ios.conf
#
# 建議流程（在品牌 repo 內）：
#   git tag pre-rebrand
#   bash Tools/brand/rebrand-ios.sh Tools/brand/simon-ios.conf
#   python3 Tools/brand/preflight-ios.py Tools/brand/simon-ios.conf
#   git add -A && git commit -m "rebrand: apply simon branding"
#
# 一次性腳本：在已換裝的 tree 重跑無效（關鍵字已被換掉）。
# 要改參數 → git reset --hard pre-rebrand 再跑。
#
# 依據: Tools/brand/rebrand-inventory.md（8 路掃描產物,對 pin tag 逐行查證）
# ---------------------------------------------------------------------------
set -euo pipefail

CONF="${1:-}"
[[ -n "$CONF" && -f "$CONF" ]] || { echo "用法: bash Tools/brand/rebrand-ios.sh <conf>" >&2; exit 1; }
# shellcheck source=/dev/null
source "$CONF"
: "${BRAND_ID:?}" "${APP_NAME:?}" "${BUNDLE_ID_PREFIX:?}" "${BUNDLE_ID_BASE:?}"
: "${BRAND_HOST:?}" "${PRIMARY_COLOR:?}" "${URL_SCHEME:?}" "${LOGO_SRC:?}" "${OAUTH_CLIENT_ID:?}"
ICON_BG="${ICON_BG:-$PRIMARY_COLOR}"
PRIMARY_COLOR_TINT="${PRIMARY_COLOR_TINT:-$PRIMARY_COLOR}"
APP_NAME_C99="$(echo "$APP_NAME" | tr -d ' ')"   # SimonSmartHome

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

say() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()  { printf '  ✓ %s\n' "$*"; }
die() { printf '  ✗ %s\n' "$*" >&2; exit 1; }

# 一次性防呆
grep -q 'io.robbie' Configuration/HomeAssistant.xcconfig || die "看起來已換裝過（找不到 io.robbie）。git reset --hard pre-rebrand 後再跑。"
[[ -f "$LOGO_SRC" ]] || die "LOGO_SRC 不存在: $LOGO_SRC"

# macOS sed
sedi() { sed -i '' "$@"; }
# 檔案內必須發生替換,否則 fail-fast（防 pattern 飄掉）
must_sed() { # must_sed <file> <sed-expr> <label>
  local f="$1" expr="$2" label="$3"
  local before; before=$(md5 -q "$f")
  sedi "$expr" "$f"
  [[ "$before" != "$(md5 -q "$f")" ]] || die "pattern 沒命中: $label ($f)"
  ok "$label"
}

PBX="HomeAssistant.xcodeproj/project.pbxproj"
XCC="Configuration/HomeAssistant.xcconfig"

# ---------------------------------------------------------------------------
say "1/10 Brand.xcconfig + Bundle ID 拼接規則"
cat > Configuration/Brand.xcconfig <<EOF
// Brand.xcconfig — generated by rebrand-ios.sh, do not edit by hand
BRAND_ID = ${BRAND_ID}
BRAND_APP_NAME = ${APP_NAME}
BRAND_HOST = ${BRAND_HOST}
BRAND_URL_SCHEME = ${URL_SCHEME}
BRAND_BUNDLE_BASE = ${BUNDLE_ID_BASE}
EOF
ok "Configuration/Brand.xcconfig"

grep -q 'Brand.xcconfig' "$XCC" || sedi '1i\
#include "Brand.xcconfig"
' "$XCC"
must_sed "$XCC" "s|^BUNDLE_ID_PREFIX = io.robbie\$|BUNDLE_ID_PREFIX = ${BUNDLE_ID_PREFIX}|" "BUNDLE_ID_PREFIX → ${BUNDLE_ID_PREFIX}"
must_sed "$XCC" 's|\${BUNDLE_ID_PREFIX}\.HomeAssistant\${BUNDLE_ID_SUFFIX}|${BUNDLE_ID_PREFIX}.$(BRAND_BUNDLE_BASE)${BUNDLE_ID_SUFFIX}|' "PRODUCT_BUNDLE_IDENTIFIER → \$(BRAND_BUNDLE_BASE)"
must_sed "$XCC" "s|^PRODUCT_NAME = HomeAssistant-\$(TARGET_NAME)\$|PRODUCT_NAME = ${APP_NAME_C99}-\$(TARGET_NAME)|" "PRODUCT_NAME fallback"

# WatchApp companion ID（Info.plist 內硬編碼拼接）
must_sed Sources/WatchApp/Info.plist 's|\$(BUNDLE_ID_PREFIX)\.HomeAssistant\$(BUNDLE_ID_SUFFIX)|$(BUNDLE_ID_PREFIX).'"${BUNDLE_ID_BASE}"'$(BUNDLE_ID_SUFFIX)|' "WKCompanionAppBundleIdentifier"
must_sed Sources/Extensions/Watch/Resources/Info.plist 's|\$(BUNDLE_ID_PREFIX)\.HomeAssistant\$(BUNDLE_ID_SUFFIX)|$(BUNDLE_ID_PREFIX).'"${BUNDLE_ID_BASE}"'$(BUNDLE_ID_SUFFIX)|' "WKAppBundleIdentifier (watch ext)"
# LocalPushEvent / PushServer 硬編碼 app_id（推播本期不做,仍保持一致）
must_sed Sources/Shared/Notifications/LocalPush/LocalPushEvent.swift "s|io\.robbie\.HomeAssistant|${BUNDLE_ID_PREFIX}.${BUNDLE_ID_BASE}|g" "LocalPushEvent app_id"
sedi "s|io\.robbie\.HomeAssistant|${BUNDLE_ID_PREFIX}.${BUNDLE_ID_BASE}|g" Sources/PushServer/Sources/App/routes.swift || true
ok "PushServer 預設 topic（附帶）"

# ---------------------------------------------------------------------------
say "2/10 Entitlements 品牌代換 + 雙軌（dev 精簡 / release 完整）"
ENT=Configuration/Entitlements
for f in App-ios App-catalyst Extension-ios Extension-catalyst; do
  must_sed "$ENT/$f.entitlements" "s|\.homeassistant\$(BUNDLE_ID_SUFFIX)|.${BUNDLE_ID_BASE}\$(BUNDLE_ID_SUFFIX)|; s|\.HomeAssistant\$(BUNDLE_ID_SUFFIX)|.${BUNDLE_ID_BASE}\$(BUNDLE_ID_SUFFIX)|" "$f 品牌代換"
done
# release 完整版: applinks 改品牌網域
must_sed "$ENT/App-ios.entitlements" "s|applinks:my\.home-assistant\.io|applinks:${BRAND_HOST}|; s|applinks:\*\.home-assistant\.io|applinks:${BRAND_HOST}|; s|applinks:home-assistant\.io|applinks:${BRAND_HOST}|" "App-ios applinks → ${BRAND_HOST}"
sedi "s|applinks:my\.home-assistant\.io|applinks:${BRAND_HOST}|; s|applinks:\*\.home-assistant\.io|applinks:${BRAND_HOST}|; s|applinks:home-assistant\.io|applinks:${BRAND_HOST}|" "$ENT/App-catalyst.entitlements" || true

# 產生雙軌目錄
mkdir -p "$ENT/dev" "$ENT/release"
for f in App-ios App-catalyst Extension-ios Extension-catalyst Launcher; do
  cp "$ENT/$f.entitlements" "$ENT/release/$f.entitlements"
  cp "$ENT/$f.entitlements" "$ENT/dev/$f.entitlements"
done
# dev 精簡: 拔免費 Personal Team 簽不了的 key
strip_key() { /usr/libexec/PlistBuddy -c "Delete :$2" "$1" 2>/dev/null || true; }
DEVAPP="$ENT/dev/App-ios.entitlements"
for k in aps-environment com.apple.developer.associated-domains \
         com.apple.developer.nfc.readersession.formats com.apple.developer.siri \
         com.apple.developer.usernotifications.communication \
         com.apple.developer.usernotifications.time-sensitive \
         com.apple.developer.networking.wifi-info; do strip_key "$DEVAPP" "$k"; done
for k in aps-environment com.apple.developer.associated-domains \
         com.apple.developer.usernotifications.communication; do strip_key "$ENT/dev/App-catalyst.entitlements" "$k"; done
strip_key "$ENT/dev/Extension-ios.entitlements" "com.apple.developer.networking.wifi-info"
ok "dev 精簡版產生（拔 aps/applinks/NFC/Siri/wifi-info/通訊通知）"

# pbxproj 的 CODE_SIGN_ENTITLEMENTS 改走 $(ENTITLEMENTS_VARIANT)
# 兩種形態都要吃: CODE_SIGN_ENTITLEMENTS = path; 與 "CODE_SIGN_ENTITLEMENTS[sdk=macosx*]" = "path";
perl -pi -e 's{("?)CODE_SIGN_ENTITLEMENTS((?:\[[^\]]*\])?)("?) = "?(Configuration/Entitlements/[A-Za-z-]+\.entitlements)"?;}{my ($q1,$br,$q3,$p)=($1,$2,$3,$4); $p =~ s|Entitlements/|Entitlements/\$(ENTITLEMENTS_VARIANT)/|; "${q1}CODE_SIGN_ENTITLEMENTS${br}${q3} = \"${p}\";"}ge' "$PBX"
grep -q 'ENTITLEMENTS_VARIANT' "$PBX" || die "pbxproj CODE_SIGN_ENTITLEMENTS 改寫沒命中"
! grep -E 'CODE_SIGN_ENTITLEMENTS[^=]* = "?Configuration/Entitlements/[A-Za-z-]+\.entitlements' "$PBX" >/dev/null || die "仍有 CODE_SIGN_ENTITLEMENTS 未改走 ENTITLEMENTS_VARIANT(catalyst 引號形態?)"
ok "pbxproj CODE_SIGN_ENTITLEMENTS → \$(ENTITLEMENTS_VARIANT)"
grep -q '^ENTITLEMENTS_VARIANT' Configuration/HomeAssistant.debug.xcconfig 2>/dev/null || \
  printf '\nENTITLEMENTS_VARIANT = dev\n' >> Configuration/HomeAssistant.debug.xcconfig
grep -q '^ENTITLEMENTS_VARIANT' Configuration/HomeAssistant.release.xcconfig 2>/dev/null || \
  printf '\nENTITLEMENTS_VARIANT = release\n' >> Configuration/HomeAssistant.release.xcconfig
ok "Debug=dev / Release=release"

# ---------------------------------------------------------------------------
say "3/10 OAuth 常數（Debug/Release 統一 ${URL_SCHEME},client_id → conf）"
OAD=Sources/App/Onboarding/API/OnboardingAuthDetails.swift
must_sed "$OAD" "s|https://home-assistant\.io/iOS/dev-auth|${OAUTH_CLIENT_ID}|; s|https://home-assistant\.io/iOS|${OAUTH_CLIENT_ID}|" "clientID ×2"
must_sed "$OAD" "s|homeassistant-dev://auth-callback|${URL_SCHEME}://auth-callback|; s|homeassistant://auth-callback|${URL_SCHEME}://auth-callback|" "redirectURI ×2"
must_sed "$OAD" "s|scheme = \"homeassistant-dev\"|scheme = \"${URL_SCHEME}\"|; s|scheme = \"homeassistant\"|scheme = \"${URL_SCHEME}\"|" "scheme ×2"
ATR=Sources/Shared/API/Authentication/AuthenticationRoutes.swift
must_sed "$ATR" "s|https://home-assistant\.io/iOS/dev-auth|${OAUTH_CLIENT_ID}|; s|https://home-assistant\.io/iOS|${OAUTH_CLIENT_ID}|" "AuthenticationRoutes clientID"
must_sed Sources/App/Onboarding/API/OnboardingAuthLoginViewController.swift \
  "s|hasPrefix(\"homeassistant\")|hasPrefix(\"${URL_SCHEME}\")|" "redirect 攔截 hasPrefix"

# ---------------------------------------------------------------------------
say "4/10 URL scheme（deeplink + Info.plist 註冊,統一 ${URL_SCHEME}）"
must_sed Sources/Shared/Environment/AppConstants.swift \
  "s|\"homeassistant-dev://\"|\"${URL_SCHEME}://\"|; s|\"homeassistant://\"|\"${URL_SCHEME}://\"|" "AppConstants.deeplinkURL"
must_sed "$PBX" "s|ENV_URL_HANDLER = \"homeassistant-dev\";|ENV_URL_HANDLER = \"${URL_SCHEME}\";|" "ENV_URL_HANDLER (Debug)"
must_sed "$PBX" "s|ENV_URL_HANDLER = homeassistant;|ENV_URL_HANDLER = ${URL_SCHEME};|" "ENV_URL_HANDLER (Release)"
# 測試 fixtures（narrow patterns only,絕不碰 userInfo["homeassistant"] 協定 key）
for tf in Tests/App/AppConstants.test.swift \
          Tests/App/Auth/OnboardingAuthLoginViewController.test.swift \
          Tests/App/Auth/OnboardingAuthLoginImpl.test.swift \
          Tests/Shared/URLComponents+WidgetAuthenticity.test.swift; do
  [[ -f "$tf" ]] && sedi "s|homeassistant-dev://|${URL_SCHEME}://|g; s|homeassistant://|${URL_SCHEME}://|g; s|hasPrefix(\"homeassistant\")|hasPrefix(\"${URL_SCHEME}\")|g" "$tf"
done
ok "測試 fixtures"

# ---------------------------------------------------------------------------
say "5/10 顯示名稱（PRODUCT_NAME / CFBundleDisplayName）"
must_sed "$PBX" "s|PRODUCT_NAME = HomeAssistant;|PRODUCT_NAME = ${APP_NAME_C99};|g" "PRODUCT_NAME = ${APP_NAME_C99}"
must_sed "$PBX" "s|Home Assistant Δ|${APP_NAME} Δ|g" "App Debug 顯示名 + TEST_HOST（Δ 保留）"
must_sed "$PBX" "s|PRODUCT_NAME = \"Home Assistant Launcher\";|PRODUCT_NAME = \"${APP_NAME} Launcher\";|g" "Launcher 顯示名"
sedi "s|PRODUCT_NAME = \"Home Assistant\";|PRODUCT_NAME = \"${APP_NAME}\";|g" "$PBX"
ok "App Release 顯示名"
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}" Sources/WatchApp/Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}" Sources/Extensions/Share/Resources/Info.plist
ok "WatchApp / Share extension CFBundleDisplayName"

# ---------------------------------------------------------------------------
say "6/10 本地化字串（34 語系 × 5 表,白名單保護）"
python3 Tools/brand/replace_strings.py --app-name "$APP_NAME" --repo-root "$REPO_ROOT"

# ---------------------------------------------------------------------------
say "7/10 品牌色（#009AC7 → #${PRIMARY_COLOR}）"
python3 - "$REPO_ROOT" "$PRIMARY_COLOR" "$PRIMARY_COLOR_TINT" <<'PYEOF'
import json, sys, os
root, primary, tint = sys.argv[1], sys.argv[2], sys.argv[3]
def rgb(hexstr): return [f"0x{hexstr[0:2].upper()}", f"0x{hexstr[2:4].upper()}", f"0x{hexstr[4:6].upper()}"]
def set_colors(path, mapping):
    p = os.path.join(root, path)
    with open(p) as f: data = json.load(f)
    changed = 0
    for c in data.get("colors", []):
        comp = c.get("color", {}).get("components")
        if not comp: continue
        key = (comp.get("red","").upper(), comp.get("green","").upper(), comp.get("blue","").upper())
        for old, new in mapping.items():
            if key == tuple(x.upper() for x in old):
                comp["red"], comp["green"], comp["blue"] = new
                changed += 1
    if not changed: raise SystemExit(f"色值沒命中: {path}")
    with open(p, "w") as f: json.dump(data, f, indent=2); f.write("\n")
    print(f"  ✓ {path} ({changed} 處)")
P = rgb(primary); T = rgb(tint)
HA = ("0x00","0x9A","0xC7")
set_colors("Sources/App/Resources/Assets.xcassets/accentColor.colorset/Contents.json", {HA: P})
set_colors("Sources/Shared/Assets/Colors.xcassets/haPrimary.colorset/Contents.json", {HA: P})
set_colors("Sources/Shared/Assets/Colors.xcassets/ha-color-border-primary-quiet.colorset/Contents.json",
           {HA: P, ("0xB9","0xE6","0xFC"): T})
# Widgets 缺 AccentColor.colorset（pbxproj 指名大寫 A）→ 補一個
wdir = os.path.join(root, "Sources/Extensions/Widgets/Resources/Assets.xcassets/AccentColor.colorset")
os.makedirs(wdir, exist_ok=True)
with open(os.path.join(wdir, "Contents.json"), "w") as f:
    json.dump({"colors":[{"color":{"color-space":"srgb","components":{"alpha":"1.000","blue":P[2],"green":P[1],"red":P[0]}},"idiom":"universal"}],"info":{"author":"xcode","version":1}}, f, indent=2); f.write("\n")
print("  ✓ Widgets AccentColor.colorset（補建）")
PYEOF
must_sed Sources/Shared/DesignSystem/BaseColors.swift "s|0xFF18BCF2|0xFF${PRIMARY_COLOR}|" "BaseColors.brandBlue"
for f in Sources/App/Settings/LiveActivity/LiveActivitySettingsView.swift \
         Sources/Extensions/Watch/Home/MagicItemRow/WatchFolderRow.swift \
         Sources/Extensions/Widgets/LiveActivity/HALockScreenView.swift; do
  sedi "s|03A9F4|${PRIMARY_COLOR}|g" "$f"
done
ok "Swift 硬編碼 HA 藍 ×4 檔"

# ---------------------------------------------------------------------------
say "8/10 icon / logo 資產（壓平 alpha → #${ICON_BG}）"
python3 Tools/brand/gen_icons.py --logo "$LOGO_SRC" --bg "$ICON_BG" --repo-root "$REPO_ROOT"

# ---------------------------------------------------------------------------
say "9/10 官網/文件入口連結 → https://${BRAND_HOST}（STUN/推播 API/NFC/my.ha 保留）"
# AppConstants WebURLs + ExternalLink + 散落的 9 個 doc 連結
DOCFILES=(
  Sources/Shared/Environment/AppConstants.swift
  Sources/Shared/ExternalLink.swift
  Sources/App/MainWindowGroupCommands.swift
  Sources/App/AppDelegate.swift
  Sources/App/Settings/Settings/SettingsView.swift
  Sources/App/Settings/AppleWatch/Complications/ComplicationEditView.swift
  Sources/App/Settings/AppleWatch/Complications/ComplicationListView.swift
  Sources/App/Settings/Notifications/NotificationCategoryListView.swift
  Sources/App/Settings/Notifications/NotificationSettingsView.swift
  Sources/App/Settings/Notifications/NotificationCategoryEditorView.swift
  Sources/App/Settings/Notifications/NotificationSoundsView.swift
  Sources/Shared/Environment/ServerAlerter.swift
)
for f in "${DOCFILES[@]}"; do
  [[ -f "$f" ]] || die "DOCFILES 路徑不存在(檔案被移動?): $f"
  sedi "s|https://companion\.home-assistant\.io|https://${BRAND_HOST}|g; s|https://www\.home-assistant\.io|https://${BRAND_HOST}|g; s|https://alerts\.home-assistant\.io|https://${BRAND_HOST}|g; s|https://github\.com/home-assistant/iOS|https://${BRAND_HOST}|g; s|https://community\.home-assistant\.io|https://${BRAND_HOST}|g; s|https://twitter\.com/home_assistant|https://${BRAND_HOST}|g; s|https://www\.facebook\.com/[A-Za-z0-9]*|https://${BRAND_HOST}|g; s|https://ohf\.to/[A-Za-z/-]*|https://${BRAND_HOST}|g" "$f"
done
ok "入口連結替換（stun./mobile-apps./my. 開頭與 mac Updater 不動）"

# 註解裡的 homeassistant:// 也換掉（紅隊: 全數為註解,安全;避免 preflight 誤判與文件誤導）
for f in Sources/App/HAApp.swift Sources/App/Frontend/IncomingURLHandler.swift \
         Sources/Shared/Environment/AppConstants.swift; do
  sedi "s|homeassistant://|${URL_SCHEME}://|g" "$f"
done
ok "註解殘留清除 ×3 檔"

# ---------------------------------------------------------------------------
say "10/10 完成 — 後續動作"
echo "  1) python3 Tools/brand/preflight-ios.py $CONF"
echo "  2) pod install（PRODUCT_NAME 變更後重新整合）"
echo "  3) xcodebuild -workspace HomeAssistant.xcworkspace -scheme App-Debug build"
echo "  4) git add -A && git commit -m 'rebrand: apply ${BRAND_ID} branding'"
